### ISSUE TITLE
CTRL+Click (GoDoc) shortcut doesn't work on Mac

### ISSUE THREAD

**Issue by gunjan5** [dlsniper/ggg#1]
CTRL+click is system default for right click on mac, so it opens right click menu instead of Godoc.

I'd suggest changing it to Command+click for mac

jQuery KeyCode for Command is 91

**Comment by dlsniper** [comment]
Fixed in https://github.com/dlsniper/ggg/commit/ce568d648da6f69b5910a9414d43bd5e51b308ba, thanks for reporting.
